export const homePath = "/";
export const shipsMarketPath = "/ships";
export const myProfile = "/user-profile";
export const signInPath = "/sign-in";
export const gamesPath = "/games";
export const apiUrl = "/";
export const imagesPath = "../assets/images";
export const tetrisPath = "/tetris";
export const memoPath ="/memo";
